# Generated by Django 6.0.6 on 2026-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolyo', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Virgülle ayırın. Örn: Django, PostgreSQL, REST, JWT', max_length=300, verbose_name='Teknolojiler'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Projenin ekran görüntüsü (önerilir: 1600×1000 px civarı).', null=True, upload_to='portfolio/images/', verbose_name='Ekran görüntüsü'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, verbose_name='Proje linki'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
